### PR TITLE
Converts webpack to rspack

### PR DESCRIPTION
**Pull request by elliotBraem**
[rspack](https://rspack.dev/) is a rust optimized, drop-in replacement of webpack.

- [x] replaces webpack with rspack
- [x] [removes babel](https://rspack.dev/guide/migration/webpack#babel-loader--swc-loader--builtinswc-loader) and [replaces webpack packages with rspack compatible versions](https://rspack.dev/guide/migration/webpack)
- [x] [replace raw-loader with asset/source](https://rspack.dev/)
- [x] moves some dependencies to devDependencies (playwright, socket.io, prettier)
- [x] moves import map script tags into body tag (rather than after body tag)
- [x] removes webpack bundle analyzer and adds command -- this comes baked-in rspack
- [x] benchmark current dev + prod build times 
- [x] benchmark rspack dev + prod build times
- [x] benchmark current bundle size
- [x] benchmark rspack bundle size
- [ ] investigate large, unnecessary packages
     - [ ] highlight.js/lib and refactor both come from react-syntax-highlighter (used in near-social-vm), and amount to 400+ KB (solved with [NearBuilders/VM#feat/syntax-highlighter](https://github.com/NEARBuilders/VM/pull/1/files))
     - [ ] @ethersproject, @web3-onboard, @viem/_esm, @web3-onboard, @ledgerhq/connect-kit, @walletconnect - worth replacing web3-onboard with wagmi? 
     - [ ] why is near-wallet-selector so large? 60KB

| near-bos-webcomponent | Webpack | Rspack |
|--------|--------|--------|
| dev build time | 20.01s | 8.28 s |
| prod build time | 48.74s | 10.54 s |
| bundle size (stat) | 15.08 MB | 12.38 MB |
| bundle size (parsed) | 8.36 MB | 6.70 MB |
| bundle size (gzipped) | 2.74 MB | 2.01 MB |

### CODE REVIEW

**Comment by petersalomonsen** [comment]
Looks great @elliotBraem . I did not know about rspack. Are you able to make the test pass too?

**Comment by elliotBraem** [comment]
@race-of-sloths include

**Comment by race-of-sloths** [comment]
@elliotBraem Thank you for your contribution! Your pull request is now a part of the [Race of Sloths](https://race-of-sloths.com)!
Do you want to apply for monthly streak? Get 8+ score for a single PR this month and receive boost for race-of-sloths!

[<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://badge.race-of-sloths.com/elliotBraem?type=bot&theme=dark">
    <source media="(prefers-color-scheme: light)" srcset="https://badge.race-of-sloths.com/elliotBraem?type=bot&theme=light">
    Shows profile picture for the author of the PR
</picture>](https://race-of-sloths.com/profile/elliotBraem)


<details><summary>Current status: <i>waiting for scoring</i></summary>

We're waiting for maintainer to score this pull request with `@race-of-sloths score [0,1,2,3,5,8,13]` command. Alternatively, autoscoring [1,2] will be applied for this pull request

</details><details><summary>What is the Race of Sloths</summary>
<p>
Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag @race-of-sloths inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths.com/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths.com/profile/elliotBraem)

For maintainers:
- Score pull requests that participate in the Race of Sloths
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths.com) for additional details!
</p>
</details> 

<details>
<summary>Bot commands</summary>

- For contributors
  - **Include a PR:** `@race-of-sloths include` to enter the Race with your PR
- For maintainers:
  - **Invite contributor** `@race-of-sloths invite` to invite the contributor to participate in a race or include it, if it's already a runner.
  - **Assign points:** `@race-of-sloths score [1/2/3/5/8/13]` to award points based on your assessment.
  - **Reject this PR:** `@race-of-sloths exclude` to send this PR back to the drawing board.
  - **Exclude repo:** `@race-of-sloths pause` to stop bot activity in this repo until `@race-of-sloths unpause` command is called

</details>

**Comment by elliotBraem** [comment]
@petersalomonsen, yeah! Rspack is a pretty cool project; it's a bit newer too but seems to be gaining more traction because it's a drop-in replacement; it barely needed any additional config besides using the rspack versions of the plugins.  

Thanks for pointing out the tests -- it looks like tests were failing to start because of a bad lockfile and then it turns out [zavodil.near/widget/Lido](https://near.social/#/zavodil.near/widget/Lido) uses an [expired subgraph url](https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2), so the widget no longer works. I swapped it out for [meta-pool-official.near/widget/MetaPoolStakeEth](https://near.social/meta-pool-official.near/widget/MetaPoolStakeEth).

They're working now and this is ready to merge then.

**Comment by elliotBraem** [comment]
I created separate tickets #47 and #48 just for future reference, if it's ever worthwhile to improve on.

**Comment by race-of-sloths** [comment]
🥁  __Score it!__

@elliotBraem, please ask your peers to score the PR using `@race-of-sloths score [1/2/3/5/8/13]`.
If no scoring is provided within 24 hours, this PR will be scored as 1 🦥

**Pull request merged**
